name: 'Tauri Build'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-22.04, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          
      - name: Install dependencies for Linux
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt update
          sudo apt install -y libwebkit2gtk-4.1-dev librsvg2-dev

      - name: Install NSIS for Windows
        if: matrix.platform == 'windows-latest'
        run: |
          choco install nsis

      - name: Install app dependencies
        run: |
          cd numwork-studio-app
          npm install

      # --- Build for Windows (avec target GNU)
      - name: Build Tauri app (Windows)
        if: matrix.platform == 'windows-latest'
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PATH: numwork-studio-app
        with:
          command: cargo tauri build
          args: '--target x86_64-pc-windows-gnu'

      # --- Build for Linux & macOS
      - name: Build Tauri app (Linux/macOS)
        if: matrix.platform != 'windows-latest'
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PATH: numwork-studio-app
        with:
          command: cargo tauri build
